# Generated by Django 6.0.1 on 2026-01-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_alter_entry_options_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='last_edited_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
